// console.dir(document.body);
// console.dir(document.body.style.background="pink");

// let x=document.getElementsByTagName("p");
// console.dir(x);


// let x=document.getElementById("myid");
// console.dir(x);


// let x=document.getElementsByClassName("class2");
// console.log(x);



// let x=document.querySelectorAll("p")[1]
// console.dir(x);



// let x=document.querySelectorAll("#class2");
// console.dir(x);



// let x=document.querySelector("p");





