// console.dir(document.body);
// console.dir(document.body.style.background="pink");

// let x=document.getElementsByTagName("p");
// console.dir(x);


// let x=document.getElementById("myid");
// console.dir(x);


// let x=document.getElementsByClassName("class2");
// console.log(x);



// let x=document.querySelectorAll("p")[1]
// console.dir(x);



// let x=document.querySelectorAll("#class2");
// console.dir(x);



// let x=document.querySelector("p");





// let x=document.querySelector("h1");
// console.log(x.getAttribute("id"));
// x.setAttribute("id","Hello Germany!!");
// // console.log(x.getAttribute("id"));




// let x=document.querySelector(".box");
// x.style.backgroundColor="pink";
// x.innerText="Anwesha";
// x.style.fontSize="20";



// let x=document.querySelector("div");
// let ele=document.createElement("div");
// ele.innerHTML="<b>Hello Div</b>";
// x.before(ele);
// x.remove();


